
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 27 22:49:10 ICT 2017
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SHORT = 63;
  public static final int SIGNED = 64;
  public static final int LEFT_ASSIGN = 73;
  public static final int TIMES = 29;
  public static final int COMMENTLINE = 51;
  public static final int BOOL = 3;
  public static final int MOD_ASSIGN = 74;
  public static final int OR_OP = 33;
  public static final int LCURLY = 18;
  public static final int SUB_ASSIGN = 45;
  public static final int AND_OP = 32;
  public static final int CONST = 89;
  public static final int REALLITERAL = 16;
  public static final int REGISTER = 62;
  public static final int ENUM = 59;
  public static final int SIZEOF = 41;
  public static final int QUESTIONMAR = 86;
  public static final int INC_OP = 80;
  public static final int COMMA = 24;
  public static final int GE_OP = 39;
  public static final int DEC_OP = 81;
  public static final int RPAREN = 23;
  public static final int AND_ASSIGN = 75;
  public static final int COMMENTBLOCK = 50;
  public static final int DOUBLE = 58;
  public static final int STRUCT = 43;
  public static final int LE_OP = 38;
  public static final int LPAREN = 22;
  public static final int VERTICALBAR = 85;
  public static final int FALSE = 6;
  public static final int TILDE = 83;
  public static final int XOR_ASSIGN = 76;
  public static final int FLOAT = 90;
  public static final int GOTO = 60;
  public static final int RIGHT_ASSIGN = 72;
  public static final int FULLSTOP = 42;
  public static final int LSQBRACKET = 20;
  public static final int STRINGLITERAL = 15;
  public static final int ADD_ASSIGN = 44;
  public static final int TRUE = 5;
  public static final int LONG = 61;
  public static final int PLUS = 27;
  public static final int PERCENT = 48;
  public static final int DIVIDE = 30;
  public static final int WHILE = 10;
  public static final int UNION = 68;
  public static final int MUL_ASSIGN = 46;
  public static final int ASSIGN = 25;
  public static final int CHAR = 55;
  public static final int PTR_OP = 82;
  public static final int SWITCH = 66;
  public static final int DO = 88;
  public static final int FOR = 11;
  public static final int GREATER = 37;
  public static final int VOID = 4;
  public static final int EXTERN = 49;
  public static final int RETURN = 12;
  public static final int CHARLITERAL = 17;
  public static final int ELSE = 9;
  public static final int BREAK = 53;
  public static final int AMPERSAND = 40;
  public static final int INT = 2;
  public static final int INTLITERAL = 14;
  public static final int RSQBRACKET = 21;
  public static final int NULL = 7;
  public static final int EOF = 0;
  public static final int SEMICOLON = 26;
  public static final int BANG = 31;
  public static final int DEFAULT = 57;
  public static final int MINUS = 28;
  public static final int error = 1;
  public static final int RIGHT_OP = 78;
  public static final int OR_ASSIGN = 77;
  public static final int CONTINUE = 56;
  public static final int IF = 8;
  public static final int UNSIGNED = 69;
  public static final int ID = 13;
  public static final int DIV_ASSIGN = 47;
  public static final int CARET = 84;
  public static final int VOLATILE = 70;
  public static final int NE_OP = 35;
  public static final int CASE = 54;
  public static final int LESS = 36;
  public static final int ELLIPSIS = 71;
  public static final int STATIC = 65;
  public static final int TYPEDEF = 67;
  public static final int LEFT_OP = 79;
  public static final int RCURLY = 19;
  public static final int AUTO = 52;
  public static final int EQUALS = 34;
  public static final int HASH = 87;
}

